### ISSUE TITLE
Webdav server stops responding after saving some files

### ISSUE THREAD

**Issue by shm-dmitry** [chrislusf/seaweedfs#1344]
WebDav server stop responding after file with some extension was uploaded.

My configuration:
I have 3 nodes in cluster.
Every node runs 2 docker-container:
- official `cockroachdb` container for filer metadata (v.20.1.0)
- my custom `seaweedfs` container with:
> - weed master -ip=b-img02 -mdir=/opt/seaweedfs/data/master -peers=b-img00:9333,b-img01:9333,b-img02:9333 -defaultReplication=200
> - weed volume -ip=b-img02 -mserver=b-img00:9333,b-img01:9333,b-img02:9333 -dataCenter=b-img02 -rack=rack -dir=/opt/seaweedfs/data/
> - weed filer -collection=filer -defaultReplicaPlacement=200
> - weed webdav
Weed version: 30GB 1.79

![Screenshot_20200603_140300](https://user-images.githubusercontent.com/19342331/83629530-f01def00-a5a2-11ea-8306-2f21ed148bde.png)

All works fine until I trying to upload file in filer.

In examples I create test file, upload it into filer and download from webdav.

Example#1 - all works fine
```
echo ok > data.html

curl -F file=@data.html http://b-img00:8888/
>> {"name":"data.html","size":3,"fid":"7,08ba03a642ff84","url":"http://b-img02:8080/7,08ba03a642ff84"}

curl -vvv http://b-img00:7333/data.html
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to b-img00 (x.x.x.x) port 7333 (#0)
> GET /data.html HTTP/1.1
> Host: b-img00:7333
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 3
< Content-Type: text/html; charset=utf-8
< Etag: "161503d94245de003"
< Last-Modified: Wed, 03 Jun 2020 11:04:35 GMT
< Date: Wed, 03 Jun 2020 11:04:57 GMT
<
ok
* Connection #0 to host b-img00 left intact

curl -X DELETE -vvv http://b-img00:7333/data.html
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to b-img00 (x.x.x.x) port 7333 (#0)
> DELETE /data.html HTTP/1.1
> Host: b-img00:7333
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< Date: Wed, 03 Jun 2020 11:08:15 GMT
<
* Connection #0 to host b-img00 left intact
```

Ok. Example#2 - I change file extention from `.html` to `.txt`
After file uploaded webdav stops to serv folder with this file (it can be downloaded via filer successfully).
Another folders in webdav works fine.

```
echo ok > data.txt

curl -F file=@data.txt http://b-img00:8888/

curl -vvv http://b-img00:7333/data.txt
*   Trying xx.xx.xx.xx...
* TCP_NODELAY set
* Connected to b-img00 (xx.xx.xx.xx) port 7333 (#0)
> GET /data.txt HTTP/1.1
> Host: b-img00:7333
> User-Agent: curl/7.58.0
> Accept: */*
>
(( I await some time - but no response received ))
^C

curl -vvv http://b-img00:8888/data.txt
*   Trying xx.xx.xx.xx...
* TCP_NODELAY set
* Connected to b-img00 (xx.xx.xx.xx) port 8888 (#0)
> GET /data.txt HTTP/1.1
> Host: b-img00:8888
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Disposition: inline; filename="data.txt"
< Content-Length: 3
< Content-Type: text/plain
< Etag: "908e596f"
< Last-Modified: Wed, 03 Jun 2020 11:09:35 GMT
< Date: Wed, 03 Jun 2020 11:10:06 GMT
<
ok
* Connection #0 to host b-img00 left intact

curl -X DELETE http://b-img00:8888/data.txt
(ok)
```

**Comment by chrislusf** [comment]
can not reproduce though.

**Comment by shm-dmitry** [comment]
@chrislusf , can I help you with logs or something else?
I think it is tied with mime-types - error reproduces dependency from file extension.
You can try another extension, or file without extension.

**Comment by chrislusf** [comment]
Maybe you can use this to see some logs
```
weed -v=4 webdav
```

**Comment by shm-dmitry** [comment]
@chrislusf 
```
{"log":"I0604 11:37:58    24 webdav_server.go:185] WebDavFileSystem.OpenFile /data.txt 0\n","stream":"stderr","time":"2020-06-04T08:37:58.953018675Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:564] WebDavFile.Stat /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.957356212Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.960742411Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [0,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968461076Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968490083Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968501469Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968511504Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968521362Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968728768Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.96878184Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968798419Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.96880846Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968817964Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968827532Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968837076Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968846724Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968856182Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968865502Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:462] WebDavFileSystem.Read /data.txt\n","stream":"stderr","time":"2020-06-04T08:37:58.968878771Z"}
{"log":"I0604 11:37:58    24 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [3,3)\n","stream":"stderr","time":"2020-06-04T08:37:58.968999023Z"}
```

Lines `WebDavFileSystem.Read` repeated infinitely.

**Comment by chrislusf** [comment]
Here are my logs:
```
I0604 09:55:04 58098 webdav_server.go:185] WebDavFileSystem.OpenFile /data.txt 0
I0604 09:55:04 58098 webdav_server.go:564] WebDavFile.Stat /data.txt
I0604 09:55:04 58098 webdav_server.go:543] WebDavFile.Seek /data.txt 0 2
I0604 09:55:04 58098 webdav_server.go:543] WebDavFile.Seek /data.txt 0 0
I0604 09:55:04 58098 webdav_server.go:462] WebDavFileSystem.Read /data.txt
I0604 09:55:04 58098 webdav_server.go:487] WebDavFileSystem.Read /data.txt: [0,3)
I0604 09:55:04 58098 webdav_server.go:450] WebDavFileSystem.Close /data.txt
```

- Why the log format is different?
- the logs are subtly different. My logs have Seek.

I am not sure why there are such differences.

**Comment by shm-dmitry** [comment]
@chrislusf 

My log format same as your - look at `log` json field.

For `data.html` I see logs as you:
```
I0605 14:44:19    15 webdav_server.go:185] WebDavFileSystem.OpenFile /data.html 0,
I0605 14:44:19    15 webdav_server.go:564] WebDavFile.Stat /data.html,
I0605 14:44:19    15 webdav_server.go:543] WebDavFile.Seek /data.html 0 2,
I0605 14:44:19    15 webdav_server.go:543] WebDavFile.Seek /data.html 0 0,
I0605 14:44:19    15 webdav_server.go:462] WebDavFileSystem.Read /data.html,
I0605 14:44:19    15 webdav_server.go:487] WebDavFileSystem.Read /data.html: [0,3),
I0605 14:44:19    15 webdav_server.go:450] WebDavFileSystem.Close /data.html
```

I watched a source code (I dont know GO language so sorry for my mistakes).

Webdav server [used](https://go.googlesource.com/net/+/master/webdav/webdav.go#219) http.serveContent method.
This method execute auto-detection content-type header bases on:

1. file [extention](https://golang.org/src/net/http/fs.go?s=3711:3815#L196).
2. parsed [content](https://golang.org/src/net/http/fs.go?s=3711:3815#L199)

After this serveContent [calls](https://golang.org/src/net/http/fs.go?s=3711:3815#L213) Seek function double times to determine size-of-content. I think this calls we see in logs.

In successfull case I see this calls, In fail case - I dont see it.
So, I think problem in step#2 of content-type detection - serveContent tried to read stream, but... it is too small?

I looked for a step#1 of content-type detection.
On unix host system it used some [predefined](https://golang.org/src/mime/type.go) extensions, and then - [used](https://golang.org/src/mime/type_unix.go) 3 mime-type files.
I looked this files in my docker-container, and not found any.

I mount `/etc/mime.types` from host system, and error is dissapier.

So I think problem in Read function - maybe it have to raise some end-of-stream error? I dont know how it must work on GO.

Can you try to delete `/etc/mime.types` file and try to repeat samples?

**Comment by chrislusf** [comment]
Thanks for all the details! 

The io.ReadAtLeast function used by http.DetectContentType has a loop. It is expecting an io.EOF error.

```
	for n < min && err == nil {
		var nn int
		nn, err = r.Read(buf[n:])
		n += nn
	}
```

**Comment by chrislusf** [comment]
Also, I am curious what your use case is for WebDAV.

**Comment by shm-dmitry** [comment]
@chrislusf 

I have file-server (3 nodes) for static files.
500k images distributed from `filer volume`.
And 10k files (`pdf` and images) distributed from `filer` store (I have to save file-name and file-path)
This files uploaded to `filer` manually.

So first usage of `webdav` - manual uploading data to file-store. Yes, I can use `scp` or `curl`.. But copy-past is more user-friendly :)

Second usage of webdav....
I cant distribute files directly from `filer` - because `filer` shows admin page allows anybody to list folder.
I tried to close this page using nginx configuration, but it was too dificullt.
So I watch to `webdav` server. It uses GET for files distribution only, and this nginx configuration helps me:
```
        location /static/ {
            limit_except GET {
                deny all;
            }

            proxy_pass http://localhost:7333 ;
            include proxy_params;

            add_header Cache-Control "max-age=86400, must-revalidate";
        }
```

**Comment by chrislusf** [comment]
Very good to learn this! This is enlightening!

**Comment by Dando-Real-ITA** [comment]
Hi,
I am currently testing SeaweedFS in a Docker Swarm enviroment ( and I created an image which supports multi master peers here: https://hub.docker.com/r/gasparekatapy/seaweedfs )

Because I can't use fuse mount in docker swarm, I am trying to solve the problem with webdav mount using davfs2, to get the nodes see the FS.
When I was trying to use the webdav mount to write files in one node and read in the other, it was always failing

Finding this issue track, I added the -v=4 to get the logs, and found the unlimited cycle loop.
Mounting /etc/mime.types ( thanks for the suggestion! ) seems to works. Why is it necessary? Can it be added to documentation?

Checking more, now.

**Comment by chrislusf** [comment]
@Dando-Real-ITA  the https://hub.docker.com/r/gasparekatapy/seaweedfs is nice. Need some description to show the difference.

Mime types are needed when uploading, to extract mime info which can be used later in http responses. Any suggestions on documentation? You can actually change the wiki directly yourself.

**Comment by Dando-Real-ITA** [comment]
I added a start.sh as a new entrypoint:

1. Detects a *peers argument

1. d



ses dig to get from the service name detected in peers, all task ips using tasks.<service_name> dns request

**Comment by chrislusf** [comment]
@Dando-Real-ITA this bug should have been resolved already. Which version are you using?

**Comment by Dando-Real-ITA** [comment]
Latest version of the image published on docker hub
Checking the file on the container where I manually mount the /etc/mime.types:
docker exec -it 66a94873e952 ls -al /etc/mime.types
-rw-r--r--    1 root     root         24301 Jul 15  2016 /etc/mime.types

On a container where I don't mount the image:
docker exec -it 64779f323dad ls -al /etc/mime.types
ls: /etc/mime.types: No such file or directory

Running the image directly:

docker pull chrislusf/seaweedfs:latest
latest: Pulling from chrislusf/seaweedfs
Digest: sha256:18707eae5a9906465d54a1274610fab7f92183e24810c3691c44b01b1a06811e
Status: Downloaded newer image for chrislusf/seaweedfs:latest
docker.io/chrislusf/seaweedfs:latest

docker run -it --entrypoint /bin/ash chrislusf/seaweedfs:latest
/ # ls -al /etc/mime*
ls: /etc/mime*: No such file or directory

**Comment by chrislusf** [comment]
> Finding this issue track, I added the -v=4 to get the logs, and found the unlimited cycle loop.

Could you please show the logs?

**Comment by Dando-Real-ITA** [comment]
Hi,
it was a read loop, kinda like https://github.com/chrislusf/seaweedfs/issues/1344#issuecomment-638709082
I prefer to not redeploy without the added /etc/mime.types because it was clogging my nodes cpu

I resolved permanently by adding /etc/mime.types to the image gasparekatapy/seaweedfs

**Comment by chrislusf** [comment]
That should have been fixed. Please help to collect the thread dump by
“kill -3” the WebDAV process.

**Comment by Dando-Real-ITA** [comment]
I was able to reproduce it, even on my image, using a file which suffix is not mapped in /etc/mime.types:

```
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:84] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.x37h86luhb8m@gpu03.nash.katapy.io    | I1014 11:26:18     1 reader_at.go:128] doReadAt [486,512), n:0, err:<nil>
```

As you can see, it is an unlimited loop - I have to force kill the logs and the process.
If I instead try to read a file which is mapped in /etc/mime.types, like a .txt or .html, it works with my image where I manually added the file.
On the original image, even a test.txt fails
The file itself is served correctly by filer, I can access it via the public URL, so the problem is only on how WebDAV tries to read it

Because it is impossible to really map all type of file suffixes to /etc/mime.types, can you make the WebDAV server indipendent to the /etc/mime.type or at least, have use default like application/octet-stream when a type is not found in /etc/mime.types?

**Comment by chrislusf** [comment]
Added a fix. The previous fix was removed somehow due to refactoring.

**Comment by Dando-Real-ITA** [comment]
Thanks you for your answers.
I pulled the latest image, Digest: sha256:098c043fa56a6c40e4a402b4998275e99657243656cf227460d3a1e013d08f5a
But, the problem is not solved:

fs_cloud_webdav.0.pxnznrc6s3u5@gpu02.nash.katapy.io    | I1014 21:05:19     1 webdav_server.go:463] WebDavFileSystem.Read /traefik_bind_config/named.conf
fs_cloud_webdav.0.pxnznrc6s3u5@gpu02.nash.katapy.io    | I1014 21:05:19     1 reader_at.go:107] ReadAt [486,512) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.pxnznrc6s3u5@gpu02.nash.katapy.io    | I1014 21:05:19     1 reader_at.go:151] doReadAt [486,512), n:0, err:<nil>
fs_cloud_webdav.0.pxnznrc6s3u5@gpu02.nash.katapy.io    | I1014 21:05:19     1 webdav_server.go:489] WebDavFileSystem.Read /traefik_bind_config/named.conf: [486,486)

Now, I tested with other files, and I see that it tries always to read 512 bytes, which is what happens in detectMimeType: https://github.com/chrislusf/seaweedfs/blob/387ab6796f274151f802ccdab8756b959b5fb1cb/weed/command/filer_copy.go#L499
And in http.DetectContentType: https://golang.org/pkg/net/http/#DetectContentType

Now, if I use my image, with the extension "conf" added to /etc/mime.types as an application/octet-stream, based on the latest of your images, it's not working anymore and I get the loop

If I use my image gasparekatapy/seaweedfs:1.2.3 which was with the /etc/mime.types and is based on your image before your latest fix, it works, I can read the file, and these are the logs:

fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:184] WebDavFileSystem.OpenFile traefik_bind_config/named.conf 0
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:570] WebDavFile.Stat traefik_bind_config/named.conf
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:549] WebDavFile.Seek traefik_bind_config/named.conf 0 2
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:549] WebDavFile.Seek traefik_bind_config/named.conf 0 0
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:463] WebDavFileSystem.Read traefik_bind_config/named.conf
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 reader_at.go:107] ReadAt [0,486) of total file size 486 bytes 1 chunk views
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 reader_at.go:139] read [0,486), 0/1 chunk 6,3c90bc9b758c [0,486)
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 reader_at.go:200] readFromWholeChunkData 6,3c90bc9b758c offset 0 [0,486) size at least 486
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 reader_at.go:204] cache hit 6,3c90bc9b758c [0,486)
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 reader_at.go:151] doReadAt [0,486), n:486, err:<nil>
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:489] WebDavFileSystem.Read traefik_bind_config/named.conf: [0,486)
fs_cloud_webdav.0.218zx18mac69@gpu01.nash.katapy.io    | I1014 21:27:22     1 webdav_server.go:451] WebDavFileSystem.Close traefik_bind_config/named.conf


Now, the difference that I see, is that the Read starts at 0.

**Maybe, can it be that, after a failed DetectContentType that reads 512 bytes ( but stops at 486 ) the file offset is not reset with a seek to 0 before the next read???**

This would explain why in "error mode", there is a loop where start == end at the end of file

**Comment by chrislusf** [comment]
can you show some more outputs including the weed version?

**Comment by chrislusf** [comment]
use the dev version. The latest is the last released version.

`docker pull chrislusf/seaweedfs:dev`

**Comment by Dando-Real-ITA** [comment]
Weed version: 
CONTAINER ID        IMAGE
71af3bda09c4        chrislusf/seaweedfs:dev

docker exec -it 71af3bda09c4 weed version:
version 30GB 2.04  linux amd64

fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:489] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones: [22,22)
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:463] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:107] ReadAt [22,512) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:151] doReadAt [22,512), n:0, err:<nil>
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:489] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones: [22,22)
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:463] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:107] ReadAt [22,512) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:151] doReadAt [22,512), n:0, err:<nil>
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:489] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones: [22,22)
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:463] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:107] ReadAt [22,512) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:151] doReadAt [22,512), n:0, err:<nil>
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:489] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones: [22,22)
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:463] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:107] ReadAt [22,512) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:151] doReadAt [22,512), n:0, err:<nil>
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:489] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones: [22,22)
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 webdav_server.go:463] WebDavFileSystem.Read /129da8ba26f203d0e2a138baa950adaa/traefik_bind_config/named.common.zones
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:107] ReadAt [22,512) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.stje3t875h27@gpu03.nash.katapy.io    | I1015 10:39:46     1 reader_at.go:151] doReadAt [22,512), n:0, err:<nil>

I can't get the start because logs are so fast because of the loop that they rotate before I can even cancel the process

**Comment by Dando-Real-ITA** [comment]
The same file, if I use my image with /etc/mime.types, with the line:
application/octet-stream			bin deploy msu msp zones conf local options

fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:356] WebDavFileSystem.Stat traefik_bind_config/named.common.zones
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:184] WebDavFileSystem.OpenFile traefik_bind_config/named.common.zones 0
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:570] WebDavFile.Stat traefik_bind_config/named.common.zones
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:451] WebDavFileSystem.Close traefik_bind_config/named.common.zones
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:184] WebDavFileSystem.OpenFile traefik_bind_config/named.common.zones 0
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:570] WebDavFile.Stat traefik_bind_config/named.common.zones
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:549] WebDavFile.Seek traefik_bind_config/named.common.zones 0 2
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:549] WebDavFile.Seek traefik_bind_config/named.common.zones 0 0
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:463] WebDavFileSystem.Read traefik_bind_config/named.common.zones
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 reader_at.go:107] ReadAt [0,22) of total file size 22 bytes 1 chunk views
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 reader_at.go:139] read [0,22), 0/1 chunk 11,3c8ea3ca3113 [0,22)
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 reader_at.go:200] readFromWholeChunkData 11,3c8ea3ca3113 offset 0 [0,22) size at least 22
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 reader_at.go:204] cache hit 11,3c8ea3ca3113 [0,22)
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 reader_at.go:151] doReadAt [0,22), n:22, err:<nil>
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:489] WebDavFileSystem.Read traefik_bind_config/named.common.zones: [0,22)
fs_cloud_webdav.0.sup1urplns31@gpu01.nash.katapy.io    | I1015 10:47:15     1 webdav_server.go:451] WebDavFileSystem.Close traefik_bind_config/named.common.zones

It has to do with  DetectContentType, with mime.types, and the read offset not resetting when a mime type is not found in /etc/mime.types

**Comment by chrislusf** [comment]
can you show the commands you used to run the docker image and how to reproduce the problem?

**Comment by Dando-Real-ITA** [comment]
The problem was specifically with small files < 512 Bytes.
See https://github.com/chrislusf/seaweedfs/pull/1540
