### ISSUE TITLE
weed-fs don't see specific volume

### ISSUE THREAD

**Issue by dadmin-admin** [chrislusf/seaweedfs#188]
We've got problem - some of our volumes are not available - `/dir/lookup?pretty=y&volumeId=244'` returns

```
{
  "volumeId": "244"
}
```

Volume server is up and connected to master server. I can get location of other volumes placed on volume server

Volume directory (in our case it's `/srv/weed-volume`) contains appropriate *.dat / *.idx files (suppose `site.b.images_244.dat` / `site.b.images_244.idx`) but `curl "http://localhost:8071/status?pretty=y"` doesn't contain this volume. 

How can I debug this situation?

weed-fs 0.65

**Comment by chrislusf** [comment]
Strange. Can you just restart the volume server and see the console output during startup?

**Comment by fedotxxl** [comment]
it prints
```
I0910 05:36:37 07121 file_util.go:20] Folder /srv/weed-volume Permission: -rwxr-xr-x
I0910 05:36:37 07121 volume.go:104] loading file /srv/weed-volume/93.idx readonly false
I0910 05:36:37 07121 store.go:213] data file /srv/weed-volume/93.dat, replicaPlacement=001 v=2 size=8 ttl=
I0910 05:36:37 07121 volume.go:104] loading file /srv/weed-volume/96.idx readonly false
I0910 05:36:37 07121 store.go:213] data file /srv/weed-volume/96.dat, replicaPlacement=001 v=2 size=8 ttl=
I0910 05:36:37 07121 volume.go:104] loading file /srv/weed-volume/97.idx readonly false
I0910 05:36:37 07121 store.go:213] data file /srv/weed-volume/97.dat, replicaPlacement=001 v=2 size=8 ttl=
I0910 05:36:37 07121 volume.go:104] loading file /srv/weed-volume/98.idx readonly false
I0910 05:36:37 07121 store.go:213] data file /srv/weed-volume/98.dat, replicaPlacement=001 v=2 size=8 ttl=
...
I0910 05:36:41 07121 store.go:220] Store started on dir: /srv/weed-volume with 214 volumes max 300
I0910 05:36:41 07121 volume.go:91] Start Seaweed volume server 0.65 at 0.0.0.0:8072

```

but `site.b.images_244.idx`/`site.b.images_244.dat` files are skipped

**Comment by fedotxxl** [comment]
```
[root@wfs2 weed-volume]# pwd
/srv/weed-volume
[root@wfs2 weed-volume]# find . | wc -l
466
``` 
it means that `/srv/weed-volume` contains 233 volumes but only 214 of them was applied

**Comment by chrislusf** [comment]
Need to verify my guess: the dot in the collection name may be causing trouble.

**Comment by fedotxxl** [comment]
nope:

1. We've got a lot of other working volumes with similar name
2. These volume worked (site.b.images_244 and other ones) - we added images and so on. We had one big volume server crash (volume process crashed). It might stoped work after those crash

**Comment by chrislusf** [comment]
can you please go to seaweedfs/go/storage/store.go, function loadExistingVlumes(), to add some print outs to see why it is not loading the file? It should be a simple listing of all the .dat files under the directory.

**Comment by fedotxxl** [comment]
Do you mean:

1. Checkout project
2. Fix
3. Compile
4. Install
5. Run it

do we have simpler way to do it?

**Comment by chrislusf** [comment]
1. checkout
  go get github.com/chrislusf/seaweedfs/go/weed
2. fix
3. install
under $GOPATH/src/github.com/chrislusf/seaweedfs/go/weed
  go install

**Comment by fedotxxl** [comment]
recompiled. Got following error messages:

```
I0923 07:37:50 12266 store.go:221] Error in NewVolumeId: strconv.ParseUint: parsing "search.files_235": invalid syntax
I0923 07:37:50 12266 store.go:221] Error in NewVolumeId: strconv.ParseUint: parsing "search.files_236": invalid syntax
I0923 07:37:50 12266 store.go:221] Error in NewVolumeId: strconv.ParseUint: parsing "search.files_238": invalid syntax
```

I have to note that `search.files_235` is only part of the filename - full filename starts with `abc.hello_search.files_235` (`abc.hello_` is not real filename but it shows you the picture)

**Comment by chrislusf** [comment]
Nice info! It does not like underscore in the collection name.

**Comment by fedotxxl** [comment]
How did it work in this case? Some of these files have size > 1gb (so we successfully uploaded files to these volumes)

**Comment by chrislusf** [comment]
Different code path. This bug seems only happen during reloading.

**Comment by fedotxxl** [comment]
we use `0.65` version. We tried to find commit which releases this version but didn't succeeded in it.

Can you:
1. Provide link to `0.65` version commit
2. Fix this bug for current version
?

I think we can patch `0.65` by ourselves based on your fix

**Comment by chrislusf** [comment]
This seems already resolved in latest code.

**Comment by chrislusf** [comment]
Fixed here: https://github.com/chrislusf/seaweedfs/commit/4b0904e9c4a06a369d666a0b730f6f573db23952#diff-776e9cf43a642a0e16f089bc8bd37211

**Comment by fedotxxl** [comment]
@chrislusf  can you provide link to commit which releases `0.65` version?

**Comment by chrislusf** [comment]
It's one release between Sep 20, 2014 and Nov 28, 2014. 

https://github.com/chrislusf/seaweedfs/commits/master/go/util/constants.go 

I missed checking in the version number.

**Comment by alexanderk23** [comment]
It's strange but it seems that the underscore bug is still present in 0.70b.

**Comment by chrislusf** [comment]
Please show the error stack trace.

**Comment by alexanderk23** [comment]
There's no errors, but volumes with underscores in collection name are invisible after server restart, as described above.
Here is console output with steps to reproduce: https://gist.github.com/alexanderk23/5d025f545d0a25727c49

**Comment by chrislusf** [comment]
Alex,

I tried on both Mac and Linux, and can not reproduce. Maybe you got an old
build. If you can build it directly that should work.

Chris
